# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e64c9042afc6471395f0806ecbf6d8b66c1b49c9b362d5baaa49551cc6f3ca2934483f7166f73d8235ba39da7d91ffd298d8a837a26d36ee80826d19b7fece5

test:
  secret_key_base: bfc67792797b0c378f3030e0cc3b14e1772ff23c5b76a311ed2ab63b0448e4a9911ad390346c1581577a06f32e4acf8838385b0b1edb43e7812c20b243e38f93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
